#
# Module manifest for module 'ExamPrep'
#
# Generated by: Jules, assistente AI
#
# Generated on: 28/09/2025
#

@{

# Script module file to process.
RootModule = 'ExamPrep.psm1'

# Version number of this module.
ModuleVersion = '4.0.0'

# ID used to uniquely identify this module
GUID = 'd2a6e9a0-1b0e-4f8a-9c7d-3d0b8f6e5a4d'

# Author of this module
Author = 'Jules, assistente AI per giancarlo.allegretti'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) 2025 Jules. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Un modulo PowerShell per preparare un PC per un esame con proctoring e ripristinare le impostazioni al termine.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Functions to export from this module
FunctionsToExport = @(
    'Start-ExamPreparation',
    'Start-ExamRestore'
)

# Private data to pass to the module scripts.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Exam', 'Proctoring', 'Optimization', 'System', 'Utility')

        # A URL to the license for this module.
        LicenseUri = ''

        # A URL to the main website for this project.
        ProjectUri = ''

        # A URL to an icon representing this module.
        IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @(
            'Versione 4.0.0: Trasformazione in modulo PowerShell professionale con configurazione esterna JSON.'
        )

    } # End of PSData hashtable

} # End of PrivateData hashtable

}